spring.cloud.gcp.sql.database-name=serving-prod
spring.cloud.gcp.sql.instance-connection-name=triangl:europe-west3:analyzing
spring.cloud.gcp.sql.jdbc-url=jdbc:mysql://google/${spring.cloud.gcp.sql.database-name}?useLegacyDatetimeCode=false&cloudSqlInstance=${spring.cloud.gcp.sql.instance-connection-name}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
spring.cloud.gcp.sql.jdbc-driver=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

utilsdb.cloud.gcp.sql.database-name=dashboard-utils
utilsdb.cloud.gcp.sql.jdbc-url=jdbc:mysql://google/${utilsdb.cloud.gcp.sql.database-name}?useLegacyDatetimeCode=false&cloudSqlInstance=${spring.cloud.gcp.sql.instance-connection-name}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
# So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
# Enforces database initialization
spring.datasource.initialization-mode=always

spring.profiles.active=production
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.time_zsone=UTC
hibernate.dialect=org.hibernate.dialect.H2Dialect
